### ISSUE TITLE
Properly handle HTML entities

### ISSUE THREAD

**Issue by avik-das** [avik-das/react-dom-assertion#2]
As per #1, HTML entities are not handled correctly, and they currently need to be specified as Unicode characters. Figure out what the fundamental mismatch is, then fix it.

**Comment by avik-das** [comment]
It looks like the JSX compiler replaces HTML entities with their Unicode variants. For example, using the [online JSX compiler](https://facebook.github.io/react/jsx-compiler.html), one can see that the following input:

```
<div>&laquo; test &raquo;</div>
```

Results in:

```
React.createElement("div", null, "« test »")
```

Okay, so far so good. Unfortunately, there's a further problem. When the string passed to `react-dom-assertion` as the _expected_ DOM tree is parsed by `jsdom`, it actually parses out entities as well! To make matters worse, because `react-dom-assertion` expects well-formed XML-like inputs, it tells `jsdom` to parse in XML mode, meaning only certain entities are replaced by `jsdom`.

For example, the following:

```
"&#65; &lt;&amp;&gt;"
```

Is parsed as:

```
"A <&>"
```

While the following:

```
"&raquo;"
```

Is left as is. I'm not sure what the best solution is, but trying to be too clever can lead to unintended warts in the library's behavior. Instead, I'm going to document what users should do as a result of this in the README.

**Comment by avik-das** [comment]
I'm closing this for now. If anyone has a better idea for how to approach this, please feel free to suggest it or pick this up.

**Comment by ivan-kleshnin** [comment]
Yes, tricky cases here. I agree to give more time of passive thinking to it.

One more thing to note: Facebook team deprecates some of their tools http://facebook.github.io/react/blog/2015/06/12/deprecating-jstransform-and-react-tools.html and proposes to use Babel instead. So I think they not gonna support their online example and it's behavior will vary from a Babel's one.

**Comment by avik-das** [comment]
> So I think they not gonna support their online example and it's behavior will vary from a Babel's one.

Thanks for the heads up. Currently, we're still using JSX, but it's good to know this change is coming...
